### ISSUE TITLE
Multiple api keys and lists

### ISSUE THREAD

**Issue by timinho** [Springest/CakePHP-Mailchimp-datasource#4]
It might be a stupid question but is there a way to override the settings (api key and list id) in a controller function?

**Comment by lizhubertz** [comment]
@timinho Hey! I know this is (years) late, but we're doing some cleanup and marking this repository as unmaintained from our end. (Definitely let us know if you'd like to help out to keep it up-to-date.) Really appreciate your interest in the project and hope that @vindia gave a solution.

**Comment by vindia** [comment]
Talking about a blast from the past :grin:
